### ISSUE TITLE
GetTradeSkillLineInfoByID error

### ISSUE THREAD

**Issue by nancikennedy** [ahakola/DMFQuest#1]
Wow Retail, 10.0.0.46340
DMFQuest, 2.1.6

Getting the following error when logging in with DMFQ loaded....
------------------------------------------------------------------------

28x Interface/AddOns/DMFQuest/DMFQuest.lua:655: attempt to call field 'GetTradeSkillLineInfoByID' (a nil value)
[string "@Interface/AddOns/DMFQuest/DMFQuest.lua"]:655: in function `UpdateProfession'
[string "@Interface/AddOns/DMFQuest/DMFQuest.lua"]:860: in function `UpdateQuests'
[string "@Interface/AddOns/DMFQuest/DMFQuest.lua"]:1222: in function `?'
[string "@Interface/AddOns/DMFQuest/DMFQuest.lua"]:1108: in function <Interface/AddOns/DMFQuest/DMFQuest.lua:1105>

Locals:
self = DMFQuestFrame {
 0 = <userdata>
 CheckDMF = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:269
 CheckPortalZone = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:345
 Buttons = <table> {
 }
 Print = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:129
 Lines = <table> {
 }
 UpdateProfession = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:643
 GetItemName = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:1017
 UpdateItems = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:517
 BuyItems = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:944
 title = FontString {
 }
 UpdateQuests = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:741
 CheckDB = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:256
 Strings = <table> {
 }
}
which = 1
id = 7
profession = <table> {
}
name = "Tailoring"
icon = 4620681
skillLevel = 0
maxSkillLevel = 0
_ = 2
_ = 178
skillLine = 197
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 2832
 2 = 2825
 3 = 2831
 4 = 2830
 5 = 2823
 6 = 2822
 7 = 2828
 8 = 2834
 9 = 2827
 10 = 2829
 11 = 2833
 12 = 2753
 13 = 2755
 14 = 2756
 15 = 2757
 16 = 2750
 17 = 2751
 18 = 2758
 19 = 2759
 20 = 2760
 21 = 2761
 22 = 2762
 23 = 2533
 24 = 2499
 25 = 2478
 26 = 2507
 27 = 2557
 28 = 2517
 29 = 2549
 30 = 2565
 31 = 2437
 32 = 2525
 33 = 2486
 34 = 2508
 35 = 2550
 36 = 2566
 37 = 2518
 38 = 2558
 39 = 2454
 40 = 2479
 41 = 2526
 42 = 2487
 43 = 2500
 44 = 2534
 45 = 2527
 46 = 2488
 47 = 2480
 48 = 2567
 49 = 2519
 50 = 2472
 51 = 2559
 52 = 2551
 53 = 2501
 54 = 2509
 55 = 2535
 56 = 2528
 57 = 2489
 58 = 2552
 59 = 2568
 60 = 2520
 61 = 2481
 62 = 2473
 63 = 2560
 64 = 2502
 65 = 2510
 66 = 2536
 67 = 2553
 68 = 2537
 69 = 2529
 70 = 2521
 71 = 2511
 72 = 2561
 73 = 2474
 74 = 2482
 75 = 2491
 76 = 2503
 77 = 2569
 78 = 2530
 79 = 2504
 80 = 2492
 81 = 2554
 82 = 2475
 83 = 2512
 84 = 2483
 85 = 2522
 86 = 2562
 87 = 2570
 88 = 2538
 89 = 2531
 90 = 2493
 91 = 2513
 92 = 2484
 93 = 2523
 94 = 2555
 95 = 2563
 96 = 2476
 97 = 2571
 98 = 2539
 99 = 2505
 100 = 2485
 101 = 2524
 102 = 2540
 103 = 2572
 104 = 2477
 105 = 2556
 106 = 2506
 107 = 2564
 108 = 2514
 109 = 2494
 110 = 2532
 111 = 2720
 112 = 2777
 113 = 2787
 114 = 2791
 115 = 2811
 116 = 2819
 117 = 2821
 118 = 2846
 119 = 2847
 120 = 773
 121 = 755
 122 = 393
 123 = 333
 124 = 202
 125 = 197
 126 = 186
 127 = 182
 128 = 171
 129 = 165
 130 = 164
}
(for control) = 1
_ = 1
skillLineID = 2832
(*temporary) = nil
(*temporary) = 2832
(*temporary) = "attempt to call field 'GetTradeSkillLineInfoByID' (a nil value)"
ProfData = <table> {
 6 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 1 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
Debug = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:119

**Comment by ahakola** [comment]
I'll look into this asap when I have time for it.

**Comment by ahakola** [comment]
Version 2.2.0 should fix this. Let me know if you run into any errors.

**Comment by nancikennedy** [comment]
This seems to be resolved.
