### ISSUE TITLE
Cooking and Leatherworking fail to show items needed

### ISSUE THREAD

**Issue by b-morgan** [ahakola/DMFQuest#11]
This is my first time doing the DMF on a Horde character on Cataclysm Classic. DMFQuest is version 3.0.9.

Cooking does not show that Simple Flour is needed but when I found a vendor that sells Simple Flour, it was automatically purchased.

Leatherworking also fails to show the items needed but does auto buy the required items at the appropriate vendor.

![image](https://github.com/user-attachments/assets/30b12d32-3359-4bf2-9e09-a780bbaa153d)

**Comment by ahakola** [comment]
I'll try to look into this. Do the view correct itself if you reload your UI for example or is it always like this?

**Comment by b-morgan** [comment]
Reload does not fix it. I'm going to try another toon with different primary professions now.

**Comment by b-morgan** [comment]
Tailoring and Alchemy don't list required items. (I'll update as I go through all my characters).

**Comment by b-morgan** [comment]
I believe the problem is the if statement on line 1425 of DMFQuest.lua only allows lines 1435-1456 to execute on retail.

I removed isRetail from the if statement but weird things happened so that's not the solution 😂

**Comment by b-morgan** [comment]
Alchemy AutoBuy works for Moonberry Juice but fails for Fizzy Faire Drink (I did accept the quest first).
```
1x DMFQuest/DMFQuest.lua:601: attempt to call field 'GetLogIndexForQuestID' (a nil value)
[string "@DMFQuest/DMFQuest.lua"]:601: in function `?'
[string "@DMFQuest/DMFQuest.lua"]:461: in function <DMFQuest/DMFQuest.lua:459>

Locals:
self = DMFQuest {
 cacheAreaNames = <table> {
 }
 itemButton6 = Button {
 }
 addonTitle = "DMFQuest 3.0.9"
 itemButton1 = Button {
 }
 itemButton7 = Button {
 }
 itemButton9 = Button {
 }
 itemButton8 = Button {
 }
 TitleText = FontString {
 }
 minimumHeight = 150
 categoryId = "DMFQuest"
 endTime = 1731218400
 itemButton3 = Button {
 }
 dirty = false
 initDone = true
 startTime = 1730613600
 ContainerText = FontString {
 }
 optionsFrame = Frame {
 }
 itemButton5 = Button {
 }
 itemButton4 = Button {
 }
 itemButton2 = Button {
 }
 fixedWidth = 256.039024
 heightPadding = 72
 portalDistance = 12.705861
 Background = Texture {
 }
 Container = Frame {
 }
 CloseButton = Button {
 }
 ProfData = <table> {
 }
 cacheItemNames = <table> {
 }
}
event = "PLAYER_INTERACTION_MANAGER_FRAME_SHOW"
interactionType = 5
(*temporary) = nil
(*temporary) = 29506
(*temporary) = "attempt to call field 'GetLogIndexForQuestID' (a nil value)"
lockAutoBuy = false
f = DMFQuest {
 cacheAreaNames = <table> {
 }
 itemButton6 = Button {
 }
 addonTitle = "DMFQuest 3.0.9"
 itemButton1 = Button {
 }
 itemButton7 = Button {
 }
 itemButton9 = Button {
 }
 itemButton8 = Button {
 }
 TitleText = FontString {
 }
 minimumHeight = 150
 categoryId = "DMFQuest"
 endTime = 1731218400
 itemButton3 = Button {
 }
 dirty = false
 initDone = true
 startTime = 1730613600
 ContainerText = FontString {
 }
 optionsFrame = Frame {
 }
 itemButton5 = Button {
 }
 itemButton4 = Button {
 }
 itemButton2 = Button {
 }
 fixedWidth = 256.039024
 heightPadding = 72
 portalDistance = 12.705861
 Background = Texture {
 }
 Container = Frame {
 }
 CloseButton = Button {
 }
 ProfData = <table> {
 }
 cacheItemNames = <table> {
 }
}
```

**Comment by ahakola** [comment]
I'll move the caching code block and test if it doesn't error in CataClassic. The Fizzy Faire Drink error is my mistake not checking if the same function exists in Retail and CataClassic when I last time tried to fix the AutoBuy for that quest.

**Comment by ahakola** [comment]
Well, the CataClassic PTR is still down due to maintenance, even though my understanding is it should have ended hours ago. I'll push the fixed DMFQuest.lua to the repo and wait until either the PTR is up or someone downloads it and tests it at real servers and reports back.

**Comment by b-morgan** [comment]
I have downloaded the file tested all but the Fizzy Faire Drink (Alchemist is done for this month).

**Comment by ahakola** [comment]
And you didn't run into any errors and the items were shown correctly?

**Comment by b-morgan** [comment]
No errors and items shown correctly. The only thing I could not test was Autobuy of Fizzy Faire Drink. Did you do a release already?

**Comment by ahakola** [comment]
Just pushed out the new version tag, should be available in Github in a minute or two and in Curseforge in 5-10 minutes. The AutoBuy should work because it is just difference in the function name (`C_QuestLog.GetLogIndexForQuestID` vs `GetQuestLogIndexByID`) with same input and output in both versions of the game.

I'm closing this now, but don't hesitate to reopen this if you still run into errors or weird things happening later.
