### ISSUE TITLE
Simple Flour for a character in Cataclysm Classic Dalaran.

### ISSUE THREAD

**Issue by b-morgan** [ahakola/DMFQuest#13]
I logged into a Cataclysm Classic toon who has their Hearthstone set to Dalaran. DMFQ (3.0.10) said I needed Simple Flour but did not auto buy when I opened a Cooking Supplies vendor that had it. I purchased it but the DMFQ frame didn't update. I found the Dalaran version of the Darkmoon Faire Mage and teleported to the staging area in Muglore. Now the DMFQ frame says I have Simple Flour.

My guess is that Dalaran needs to be added to the `capitalCityAreaIDs` and/or `subZoneAreaIDs` tables but I'm not sure how to do that.

I am sure you'll know how and I'll gladly test on Cataclysm Classic and Retail if you need me to.

( just what we needed to remove the "s" from "Professions" 😉😎😁 )

**Comment by b-morgan** [comment]
See [https://www.wowhead.com/guide/world-events/recurring/darkmoon-faire-guide#how-to-get-to-the-darkmoon-faire](https://www.wowhead.com/guide/world-events/recurring/darkmoon-faire-guide#how-to-get-to-the-darkmoon-faire) for locations of the Darkmoon Faire Mystic Mages (on retail). I'm sure there's an equivalent document for Cataclysm Classic.

**Comment by ahakola** [comment]
If I recall correctly, the AutoBuy is fired only when the DMFQuest Frame is visible and you can get the Frame to show in the faction capitals by enabling the `ShowInCapitals` setting. The capitals are defined in the `capitalCityAreaIDs` -table and it shouldn't be too hard to add Dalaran and/or Shattrath. I just have to check for the proper uiMapIDs and add them to the list.

I have to test these first to be sure to add the proper ones, but according to web sources, in CataClassic uiMapID for Dalaran is either 125 or 126 and Shattrath City should be 1955.

**Comment by b-morgan** [comment]
I had the frame showing (manually with `/dmfq`) when I purchased the Simple Flour in Dalaran so there must be additional conditions.

I've run out of toons to test with but on Cataclysm Classic, the Darkmoon Faire is every two weeks.

Let me know if you need me to verify the map ids.

**Comment by ahakola** [comment]
If you had the frame visible, then I don't know what went wrong without additional information from debug messages, but according to the code (https://github.com/ahakola/DMFQuest/blob/master/DMFQuest.lua#L608), it should have worked...

You could help me verify (some of the) uiMapIDs by going to different parts of Dalaran where there are vendors (City and Sewers, maybe check also the landing pad) and use `/dmfq test` and see what number it outputs to you on the Map-line. And if it isn't too much to ask, go do same thing in Shattrath City (Lower City, Central area and both of the landings if possible)

**Comment by ahakola** [comment]
The CataClassic PTR seems to be still down, so either I'm at peoples mercy to test these things or I have to YOLO-push these changes and hope for no errors. Maybe the PTR has been down for a long time already and I haven't just noticed it and Blizzard don't plan to bring it up until the next patch is about to come out.

**Comment by b-morgan** [comment]
I do alpha and beta versions of Skillet and Skillet-Classic. I do this by setting the tag to 3.0.11-alpha1 or 3.0.11-beta1. With a number at the end, I can have multiple alpha or beta versions. The bigwig packager handles this all automagically.

BTW, everything is down as its the weekly maintenance.

**Comment by b-morgan** [comment]
Cataclysm Classic `Dalaran Map 125 4 <various named locations including the landing pad>` and `Map 126 Dalaran 4 The Underbelly`.
```
[09:29:27] DMFQuest: TEST START:
[09:29:27] DMFQuest: - Map 1955 Shattrath City 3 Terrace of Light
[09:29:27] DMFQuest: -- Check areaIDs
[09:29:27] DMFQuest: TEST END!
[09:32:02] DMFQuest: TEST START:
[09:32:02] DMFQuest: - Map 1955 Shattrath City 3 Lower City
[09:32:02] DMFQuest: -- Check areaIDs
[09:32:02] DMFQuest: TEST END!
[09:33:29] DMFQuest: TEST START:
[09:33:29] DMFQuest: - Map 1955 Shattrath City 3 Aldor Rise
[09:33:29] DMFQuest: -- Check areaIDs
[09:33:29] DMFQuest: TEST END!
[09:33:58] DMFQuest: TEST START:
[09:33:58] DMFQuest: - Map 1955 Shattrath City 3 Scryer's Tier
[09:33:58] DMFQuest: -- Check areaIDs
[09:33:58] DMFQuest: TEST END!
```

**Comment by b-morgan** [comment]
> The CataClassic PTR seems to be still down

It is down for me as well. All the other PTRs are up. 

I'm OK with manually installing files to test if you don't want to expose everyone to our experiments.

**Comment by ahakola** [comment]
I pushed out new version with these uiMapIDs and I'm closing this issue. If in the future you still run into this same issue, feel free to reopen this or make a new issue.

If you ever need to provide debug information in the future on this addon, here how you can do it:
- If you don't already have `ChatFrame4`, open a new ChatFrame and it should automatically get name `ChatFrame4`
- Use ingame command `/dmfq debug` to enable/disable debugging
- Try to do the thing that isn't working properly and then either copy&paste or take screenshot of the debug output

**Comment by b-morgan** [comment]
`/dump ChatFrame4` shows that it exists. `/dmfq debug` prints `DMFQuest: Debug: true` but I'm not sure how to find and/or verify that debug output exists.

Something is happening in ChatFrame3.

I have General, Combat Log, LFG, and Quiet chat tabs. I believe those are ChatFrame1 through ChatFrame4. The LFG global channel is off in General and on in LFG so that channel is pretty busy. Quiet has no global channels.

In Skillet-Classic, I use `(SELECTED_CHAT_FRAME or DEFAULT_CHAT_FRAME):AddMessage(msg)` for my debug output.

How is `DEBUG_CHAT_FRAME` set?

**Comment by ahakola** [comment]
Yes I used ChatFrame3 in the past, but at some point in Retail the ChatFrame numbering increased by one so I added ChatFrame4 to the end of the list and it is possible that in Classic clients it might still output to ChatFrame3 over ChatFrame4. `DEBUG_CHAT_FRAME` isn't set by the addon, but it is a relic from the source I copied the Debug output. If you have written your own addon to collect debug outputs from all of the different addons you are writing, you can make global pointer `DEBUG_CHAT_FRAME` to catch pretty much all debug outputs from my addons, where I use the same Debug and Print functions.
