### ISSUE TITLE
InterfaceOptionsFrame nil value error

### ISSUE THREAD

**Issue by nancikennedy** [ahakola/DMFQuest#2]
In testing the for the previously reported bug, I happened to move the DMFQ window on screen and got the error below. It happens every time the window is moved by dragging it. Using the sliders in the options to change its on-screen position did not trigger this. In both cases, the error did not affect the actual saving of the window's new position.

1x Interface/AddOns/DMFQuest/DMFQuest.lua:214: attempt to index global 'InterfaceOptionsFrame' (a nil value)
[string "@Interface/AddOns/DMFQuest/DMFQuest.lua"]:214: in function <Interface/AddOns/DMFQuest/DMFQuest.lua:203>

Locals:
self = Frame {
 0 = <userdata>
}
button = "LeftButton"
x = 63.083202
y = 403.999908
(*temporary) = nil
(*temporary) = nil
(*temporary) = "BOTTOMLEFT"
(*temporary) = 63.083202
(*temporary) = 403.999908
(*temporary) = "attempt to index global 'InterfaceOptionsFrame' (a nil value)"
f = DMFQuestFrame {
 0 = <userdata>
 CheckDMF = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:269
 CheckPortalZone = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:345
 Buttons = <table> {
 }
 Print = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:129
 Lines = <table> {
 }
 UpdateProfession = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:644
 GetItemName = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:1013
 UpdateItems = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:517
 BuyItems = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:940
 title = FontString {
 }
 UpdateQuests = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:737
 CheckDB = <function> defined @Interface/AddOns/DMFQuest/DMFQuest.lua:256
 Strings = <table> {
 }
}
db = <table> {
 HideMax = false
 DeathMetalKnight = true
 ShowItemRewards = true
 FadedTreasureMap = true
 items = <table> {
 }
 TestYourStrength = true
 AutoBuy = true
 YPos = 403.999908
 PetBattle = true
 UseTimeOffset = true
 HideLow = false
 XPos = 63.083202
}
panel = DMFQuestOptions {
 0 = <userdata>
 name = "DMFQuest"
}

**Comment by ahakola** [comment]
There is always something I forget to test...

**Comment by ahakola** [comment]
Version 2.2.1 should fix this and also the unreported issue of `/dmfq config` causing same error on different line.
