### ISSUE TITLE
Evoker with no primary professions doesn't show Cooking (or Fishing)

### ISSUE THREAD

**Issue by b-morgan** [ahakola/DMFQuest#4]
My level 61 Evoker has Fishing and Cooking but no primary professions. The DMF Quest frame opens but doesn't show Cooking as available and doesn't buy Simple Flour.

**Comment by ahakola** [comment]
Probably some kind of oversight in the logic from my side, I'll have a look asap

**Comment by ahakola** [comment]
This should be fixed in 3.0.1! Don't hesitate to reopen this ticket if you still run into this same problem for any reason.
