### ISSUE TITLE
LUA error in Autobuy

### ISSUE THREAD

**Issue by dblanch369** [ahakola/DMFQuest#6]
Well I have seen this pop up today, on my Evoker.  Went to hit up my usual vendor for Autobuy, and got a LUA error, see below.  A couple of notes....

Does not have Archeology profession (most of toons do)
I had grey items in my bags that wanted to Autosell, but did not Autobuy.
Subsequent attempts to talk to the vendor, repeat the LUA error. I did a /reload and it did not fix it.

Here is the output from BugSack.

<details><summary>Details</summary>
<p>

4x DMFQuest/DMFQuest.lua:1419: attempt to index local 'prof' (a nil value)
[string "@DMFQuest/DMFQuest.lua"]:1419: in function `AutoBuyItems'
[string "@DMFQuest/DMFQuest.lua"]:569: in function <DMFQuest/DMFQuest.lua:565>

Locals:
self = DMFQuest {
 0 = <userdata>
 cacheAreaNames = <table> {
 }
 QUEST_DETAIL = <function> defined @DMFQuest/DMFQuest.lua:621
 itemButton6 = Button {
 }
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:131
 startTime = 1712451600
 MERCHANT_FILTER_ITEM_UPDATE = <function> defined @DMFQuest/DMFQuest.lua:574
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:85
 MERCHANT_UPDATE = <function> defined @DMFQuest/DMFQuest.lua:574
 QUEST_REMOVED = <function> defined @DMFQuest/DMFQuest.lua:638
 OnShow = <function> defined @SharedXML/LayoutFrame.lua:32
 addonTitle = "DMFQuest 3.0.1"
 GetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:148
 itemButton1 = Button {
 }
 GetWidthPadding = <function> defined @SharedXML/LayoutFrame.lua:168
 SKILL_LINES_CHANGED = <function> defined @DMFQuest/DMFQuest.lua:546
 itemButton7 = Button {
 }
 SetFixedWidth = <function> defined @SharedXML/LayoutFrame.lua:135
 UpdateItemButtons = <function> defined @DMFQuest/DMFQuest.lua:1051
 cacheItemNames = <table> {
 }
 SetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:143
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:73
 itemButton9 = Button {
 }
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:127
 ZONE_CHANGED_NEW_AREA = <function> defined @DMFQuest/DMFQuest.lua:476
 Layout = <function> defined @SharedXML/LayoutFrame.lua:395
 itemButton8 = Button {
 }
 UpdateTextLines = <function> defined @DMFQuest/DMFQuest.lua:1124
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 TitleText = FontString {
 }
 PLAYER_ENTERING_WORLD = <function> defined @DMFQuest/DMFQuest.lua:476
 SetHeightPadding = <function> defined @SharedXML/LayoutFrame.lua:160
 minimumHeight = 150
 optionsFrame = Frame {
 }
 categoryId = "DMFQuest"
 GetHeightPadding = <function> defined @SharedXML/LayoutFrame.lua:164
 endTime = 1713052800
 itemButton3 = Button {
 }
 dirty = false
 initDone = true
 CheckForPortalZone = <function> defined @DMFQuest/DMFQuest.lua:970
 ContainerText = FontString {
 }
 QUEST_ACCEPTED = <function> defined @DMFQuest/DMFQuest.lua:617
 itemButton10 = Button {
 }
 itemButton5 = Button {
 }
 itemButton4 = Button {
 }
 BAG_UPDATE = <function> defined @DMFQuest/DMFQuest.lua:604
 itemButton2 = Button {
 }
 AutoBuyItems = <function> defined @DMFQuest/DMFQuest.lua:1408
 GetFixedSize = <function> defined @SharedXML/LayoutFrame.lua:156
 SetFixedHeight = <function> defined @SharedXML/LayoutFrame.lua:139
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 TRADE_SKILL_LIST_UPDATE = <function> defined @DMFQuest/DMFQuest.lua:546
 PixelSnapDisabled = true
 Background = Texture {
 }
 CheckForDMF = <function> defined @DMFQuest/DMFQuest.lua:874
 Container = Frame {
 }
 heightPadding = 72
 PLAYER_INTERACTION_MANAGER_FRAME_SHOW = <function> defined @DMFQuest/DMFQuest.lua:587
 fixedWidth = 324
 UpdateProfessions = <function> defined @DMFQuest/DMFQuest.lua:1315
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:93
 ZONE_CHANGED = <function> defined @DMFQuest/DMFQuest.lua:476
 QUEST_DATA_LOAD_RESULT = <function> defined @DMFQuest/DMFQuest.lua:644
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:117
 CloseButton = Button {
 }
 ProfData = <table> {
 }
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 MarkIgnoreInLayout = <function> defined @SharedXML/LayoutFrame.lua:44
 GetFixedHeight = <function> defined @SharedXML/LayoutFrame.lua:152
 ZONE_CHANGED_INDOORS = <function> defined @DMFQuest/DMFQuest.lua:476
 IgnoreLayoutInde
</p>
</details> 

![Screenshot 2024-04-09 at 8 54 18 PM](https://github.com/ahakola/DMFQuest/assets/23128709/0a220026-8272-418f-afc6-2aeecb8d06ce)

**Comment by ahakola** [comment]
I'll add this to the list of things to fix asap

**Comment by ahakola** [comment]
Forgot to make the changes to the AutoBuy when I fixed the iteration loops on missing profession indexes. Fixed in 3.0.2!
