### ISSUE TITLE
AutoBuy not AutoBuying

### ISSUE THREAD

**Issue by Pahonix** [ahakola/DMFQuest#7]
AutoBuy function is not recognizing that I need Simple Flour from the Cooking Supplies vendor in Orgrimmar.
![image](https://github.com/ahakola/DMFQuest/assets/21016041/5c75a4e3-4ccb-42a7-9377-5e98178ab525)

**Comment by Pahonix** [comment]
Follow up to say that this also happens on another character as well. For completeness, I exited the game, deleted the SavedVariables file for DMFQuest, relaunched the game, disabled all addons except DMFQuest 3.0.2 and still AutoBuy does not function here:
![image](https://github.com/ahakola/DMFQuest/assets/21016041/19f5da97-5b5b-4083-ae6b-6aef4573b0d1)

**Comment by ahakola** [comment]
AutoBuy works only in Thunder Bluff for Horde and in Goldshire for Alliance or when talking to the drink vendor in DMF Island for the Alchemy quest.

**Comment by Pahonix** [comment]
Ah, that would explain it. Previous functionality prior to the rewrite was that as long as the addon window was open, autobuy would work. Since the teleport from Orgrimmar to Mulgore puts you right by the DMF portal and to fly up to the Thunder Bluff vendors was out of the way, I always made it a habit to just buy my materials in Org before going to Mulgore.

I will have to get used to where the various vendors are in Thunder Bluff. Thank you for this great addon!

**Comment by ahakola** [comment]
Well if it worked like that, it was a bug 😄 or at least at the moment I don't remember I had such an intention (might have just forgotten such feature)

Maybe I can add the functionality for it to work if the Frame is open at some point when I have more time.

**Comment by Pahonix** [comment]
That would be much appreciated! Perhaps also an options toggle for which city(s) to have the frame auto-open in during DMF? <3

**Comment by ahakola** [comment]
This should be now working in Vanilla and BC capitals with version 3.0.4. Don't hesitate to (re)open a ticket if you run into any issues with this feature.
