### ISSUE TITLE
New issue for 3.0.4

### ISSUE THREAD

**Issue by dblanch369** [ahakola/DMFQuest#9]
Hey Ahak, it's me again.  Got my first new one showing up in Retail, even though it's not DMF week, I'm getting this error, looks like it was checking a quest objective and is responding with a NIL.

2x DMFQuest/DMFQuest.lua:1370: attempt to get length of local 'objectives' (a nil value)
[string "@DMFQuest/DMFQuest.lua"]:1370: in function <DMFQuest/DMFQuest.lua:1205>

<details><summary>More Details</summary>
<p>

2x DMFQuest/DMFQuest.lua:1370: attempt to get length of local 'objectives' (a nil value)
[string "@DMFQuest/DMFQuest.lua"]:1370: in function <DMFQuest/DMFQuest.lua:1205>

Locals:
self = nil
questId = 29433
questIcon = 136101
questDone = false
objectives = nil
(*temporary) = 29433
(*temporary) = nil
(*temporary) = 236362
(*temporary) = "Death Metal Knight"
(*temporary) = "|cffff2020Quest not done|r"
(*temporary) = "|T%d:0|t %s
%s"
(*temporary) = FontString {
}
(*temporary) = FontString {
}
(*temporary) = FontString {
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = -6
(*temporary) = <table> {
 value = 2
}
(*temporary) = <table> {
 value = 2
}
(*temporary) = 2
(*temporary) = "attempt to get length of local 'objectives' (a nil value)"
delayLock = false
activeStrings = <table> {
 1 = FontString {
 }
 2 = FontString {
 }
}
stringPool = <table> {
}
updateCount = 5
maxProfCount = 5
ProfData = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
isRetail = true
f = DMFQuest {
 cacheAreaNames = <table> {
 }
 itemButton6 = Button {
 }
 addonTitle = "DMFQuest 3.0.4"
 itemButton1 = Button {
 }
 itemButton7 = Button {
 }
 itemButton9 = Button {
 }
 itemButton8 = Button {
 }
 TitleText = FontString {
 }
 minimumHeight = 150
 categoryId = "DMFQuest"
 endTime = 0
 itemButton3 = Button {
 }
 dirty = false
 initDone = true
 ContainerText = FontString {
 }
 optionsFrame = Frame {
 }
 itemButton10 = Button {
 }
 itemButton5 = Button {
 }
 itemButton4 = Button {
 }
 itemButton2 = Button {
 }
 startTime = 0
 PixelSnapDisabled = true
 heightPadding = 72
 Background = Texture {
 }
 Container = Frame {
 }
 fixedWidth = 324
 CloseButton = Button {
 }
 ProfData = <table> {
 }
 cacheItemNames = <table> {
 }
}
ProfessionQuestData = <table> {
 773 = <table> {
 }
 356 = <table> {
 }
 794 = <table> {
 }
 185 = <table> {
 }
 186 = <table> {
 }
 171 = <table> {
 }
 164 = <table> {
 }
 202 = <table> {
 }
 165 = <table> {
 }
 197 = <table> {
 }
 393 = <table> {
 }
 129 = <table> {
 }
 333 = <table> {
 }
 755 = <table> {
 }
 182 = <table> {
 }
}
db = <table> {
 XPos = 8.860826
 ShowItemRewards = true
 FadedTreasureMap = true
 TestYourStrength = true
 dbVersion = 1
 AutoBuy = true
 GrowDirection = 1
 UseTimeOffset = true
 FrameVertexColor = <table> {
 }
 DeathMetalKnight = true
 debug = false
 HideMax = false
 items = <table> {
 }
 TimeOffsetValue = -3
 isPTR = false
 FrameLock = false
 PetBattle = false
 YPos = 342.000122
 HideLow = true
 ShowInCapitals = false
}
L = <table> {
 Profession_NoItemsNeeded = "No items needed"
 Config_ExtraFeatures_HideLow = "Hide low skills"
 FrameTitle_Pinned = "(Pinned)"
 Config_ExtraFeatures_ShowInCapitals_Desc = "Show DMFQuest Frame while you are in any of your factions capital cities when Darkmoon Faire is available."
 Config_Frame_Pos = "%sPosition"
 Config_Misc_UseTimeOffset_Desc = "Time offset tries to correct the difference between your local time and realm time.
This offset is used to improve the detection of start and end times of Darkmoon Faire."
 ChatMessage_AutoBuy_Total = "Total:"
 Config_Activity_ShowItemRewards_Desc = "Show rewards for turn-in-item in item-tooltips in DMFQuest Frame."
 Config_Activity_TestYourStrength_Desc = "Show %s -quest for this months Darkmoon Faire in DMFQuest Frame."
 Quest_QuestNoItem = "No %s in your bags"
 Config_ExtraFeatures_HideMax_Desc = "Hide professions from DMFQuest Frame if your skill is maxed."
 Config_Frame_FrameLock_Desc = "Lock DMFQuest Frame to prevent dragging from the title bar."
 Config_Frame_TintingColor_Desc = "Change the color of the DMFQuest Frame."
 ChatMessage_Slash_Syntax = "Syntax: /dmfq (config | pin | reset)"
 Config_Activity_FadedTreasureMap_Desc = "Show %s (one time quest from item) in DMFQuest Frame."
 ChatMessage_Login_DMFWarning = "Darkmoon Faire is available!"
 Config_Misc_TimeOffsetOff = "Offset Off"
 Quest_QuestReady = "Quest ready to turn in"
 QuestTitleFix_FadedTreasureMap = "Faded Treasure Map"
 Config_Frame_Pos_Desc = "Change DMFQ Frames %sPosition."
 Config_GroupHeader_Frame = "Frame Options"
 Config_Misc_TimeOffsetValue_Desc = "Select how many hours the time is offset to match the Darkmoon Faire's start and end times to your local timezone."
 Config_Activity_Show

</p>
</details>

**Comment by ahakola** [comment]
Does this happen on login or did you have to make any actions to get this error? Can you reproduce it on demand if needed or is it random?

**Comment by CherylAoife** [comment]
I just had this happen myself, when I logged in.

**Comment by ahakola** [comment]
Let me know if this still happens with 3.0.5

**Comment by fronbow** [comment]
Hi @ahakola, it's happening for me on 3.0.5 on login
````
1x DMFQuest/DMFQuest.lua:1374: attempt to call field 'GetQuestInfo' (a nil value)
[string "@DMFQuest/DMFQuest.lua"]:1374: in function <DMFQuest/DMFQuest.lua:1205>

Locals:
self = nil
questId = 29433
questIcon = 136101
questDone = false
objectives = nil
(*temporary) = nil
(*temporary) = 29433
(*temporary) = "attempt to call field 'GetQuestInfo' (a nil value)"
delayLock = false
activeStrings = <table> {
 1 = FontString {
 }
 2 = FontString {
 }
 3 = FontString {
 }
}
stringPool = <table> {
}
updateCount = 5
maxProfCount = 5
ProfData = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
isRetail = true
f = DMFQuest {
 cacheAreaNames = <table> {
 }
 itemButton6 = Button {
 }
 addonTitle = "DMFQuest 3.0.5"
 itemButton1 = Button {
 }
 itemButton7 = Button {
 }
 itemButton9 = Button {
 }
 itemButton8 = Button {
 }
 TitleText = FontString {
 }
 minimumHeight = 150
 categoryId = "DMFQuest"
 endTime = 0
 itemButton3 = Button {
 }
 dirty = false
 initDone = true
 ContainerText = FontString {
 }
 optionsFrame = Frame {
 }
 itemButton10 = Button {
 }
 itemButton5 = Button {
 }
 itemButton4 = Button {
 }
 itemButton2 = Button {
 }
 startTime = 0
 heightPadding = 72
 Background = Texture {
 }
 Container = Frame {
 }
 fixedWidth = 324
 CloseButton = Button {
 }
 ProfData = <table> {
 }
 cacheItemNames = <table> {
 }
}
ProfessionQuestData = <table> {
 773 = <table> {
 }
 356 = <table> {
 }
 794 = <table> {
 }
 185 = <table> {
 }
 186 = <table> {
 }
 171 = <table> {
 }
 164 = <table> {
 }
 202 = <table> {
 }
 165 = <table> {
 }
 197 = <table> {
 }
 393 = <table> {
 }
 129 = <table> {
 }
 333 = <table> {
 }
 755 = <table> {
 }
 182 = <table> {
 }
}
db = <table> {
 XPos = 100.098602
 ShowItemRewards = false
 FadedTreasureMap = true
 TestYourStrength = true
 dbVersion = 1
 AutoBuy = true
 GrowDirection = 1
 UseTimeOffset = false
 FrameVertexColor = <table> {
 }
 DeathMetalKnight = true
 debug = false
 HideMax = false
 items = <table> {
 }
 TimeOffsetValue = 0
 isPTR = false
 HideLow = true
 PetBattle = true
 YPos = 317.003143
 FrameLock = false
 ShowInCapitals = false
}
L = <table> {
 Profession_NoItemsNeeded = "No items needed"
 Config_ExtraFeatures_HideLow = "Hide low skills"
 FrameTitle_Pinned = "(Pinned)"
 Config_ExtraFeatures_ShowInCapitals_Desc = "Show DMFQuest Frame while you are in any of your factions capital cities when Darkmoon Faire is available."
 Config_Frame_Pos = "%sPosition"
 Config_Misc_UseTimeOffset_Desc = "Time offset tries to correct the difference between your local time and realm time.
This offset is used to improve the detection of start and end times of Darkmoon Faire."
 ChatMessage_AutoBuy_Total = "Total:"
 Config_Activity_ShowItemRewards_Desc = "Show rewards for turn-in-item in item-tooltips in DMFQuest Frame."
 Config_Activity_TestYourStrength_Desc = "Show %s -quest for this months Darkmoon Faire in DMFQuest Frame."
 Quest_QuestNoItem = "No %s in your bags"
 Config_ExtraFeatures_HideMax_Desc = "Hide professions from DMFQuest Frame if your skill is maxed."
 Config_Frame_FrameLock_Desc = "Lock DMFQuest Frame to prevent dragging from the title bar."
 Config_Frame_TintingColor_Desc = "Change the color of the DMFQuest Frame."
 ChatMessage_Slash_Syntax = "Syntax: /dmfq (config | pin | reset)"
 Config_Activity_FadedTreasureMap_Desc = "Show %s (one time quest from item) in DMFQuest Frame."
 ChatMessage_Login_DMFWarning = "Darkmoon Faire is available!"
 Config_Misc_TimeOffsetOff = "Offset Off"
 Quest_QuestReady = "Quest ready to turn in"
 QuestTitleFix_FadedTreasureMap = "Faded Treasure Map"
 Config_Frame_Pos_Desc = "Change DMFQ Frames %sPosition."
 Config_GroupHeader_Frame = "Frame Options"
 Config_Misc_TimeOffsetValue_Desc = "Select how many hours the time is offset to match the Darkmoon Faire's start and end times to your local timezone."
 Config_Activity_ShowItemRewards = "Turn-in item rewards"
 Config_Frame_FrameLock = "Lock position"
 Config_Frame_GrowDirection_Desc = "Change the direction DMFQuest Frame grows.
%s - DMFQuest Frame is anchored from BOTTOMLEFT corner.
%s - DMFQuest Frame is anchored from TOPLEFT corner."
 Config_ExtraFeatures_AutoBuy_Desc = "AutoBuy buys quest items automatically from vendors while Darkmoon Faire is avai
````

**Comment by ahakola** [comment]
Version 3.0.6 should fix this.
